[workspace]
members = [
    "examples/notifications",
    "examples/bookkeeping",
    "examples/orders",
    "examples/simple",
    "pub-sub/in-memory",
    "pub-sub/trait", "examples/messages/order-created",
]
resolver = "2"
