[package]
name = "bookkeeping-example"
version = "0.1.0"
edition = "2021"

[dependencies]
je-created-example = { path = "../messages/je-created" }
order_created_example = { path = "../messages/order-created" }
pub-sub-trait = { path = "../../pub-sub/trait" }
